name = "2020realtorsblue"
main = "src/worker.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "2020realtors-blue"
database_id = "f097b3e5-625a-44bb-b4d5-3294feee76ed"

# KV Namespace binding
[[kv_namespaces]]
binding = "KV"
id = "618011e98fa14216abb90d2618637ee5"
preview_id = "618011e98fa14216abb90d2618637ee5"

# Environment variables
[vars]
ENVIRONMENT = "production"
JWT_SECRET = "fadfhaffklajfkafhja34502520-5472fkajfajdf-e58r"
CORS_ORIGIN = "*"
FROM_EMAIL = "info@2020realtors.com"
FROM_NAME = "20/20 Realtors"