# Cloudflare Workers configuration for the real estate application

name = "real-estate-app"
main = "src/worker.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat", "experimental"]

# Assets configuration for Wrangler 4
[assets]
directory = "./dist"
binding = "ASSETS"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "2020realtors-blue"
database_id = "f097b3e5-625a-44bb-b4d5-3294feee76ed"

# KV Namespace binding
[[kv_namespaces]]
binding = "KV"
id = "618011e98fa14216abb90d2618637ee5"
preview_id = "618011e98fa14216abb90d2618637ee5"

# Environment variables
[vars]
ENVIRONMENT = "development"
JWT_SECRET = "your-jwt-secret-here"
# Production environment
[env.production]
[env.production.vars]
ENVIRONMENT = "production"
CORS_ORIGIN = "*"
FROM_EMAIL = "info@2020realtors.com"
FROM_NAME = "20/20 Realtors"

# Secrets (set these using wrangler secret put)
# SENDGRID_API_KEY = "your-sendgrid-api-key"